services:
  db:
    image: postgres:14
    volumes:
      - ${DB_ROOT:?}:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      start_period: 10s
    logging:
      driver: fluentd
      options:
        tag: docker.jop_aoirint_com.db.{{.ID}}
        fluentd-async: "true"

  app:
    image: joplin/server:3-beta
    depends_on:
      - db
    restart: always
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL:?}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    logging:
      driver: fluentd
      options:
        tag: docker.jop_aoirint_com.app.{{.ID}}
        fluentd-async: "true"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - "127.0.0.1:22300:80"
    volumes:
      - ./nginx_templates:/etc/nginx/templates
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
    logging:
      driver: fluentd
      options:
        tag: docker.jop_aoirint_com.nginx.{{.ID}}
        fluentd-async: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
    logging:
      driver: fluentd
      options:
        tag: docker.jop_aoirint_com.cloudflared.{{.ID}}
        fluentd-async: "true"
