services:
  db:
    image: postgres:14
    volumes:
      - ${DB_ROOT:?}:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  app:
    image: joplin/server:2.13-beta
    depends_on:
      - db
    restart: always
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL:?}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - "127.0.0.1:22300:80"
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
